### PR TITLE
Don't rely on health resurrect for the colony logic

### PR DESCRIPTION
**Pull request by Mailaender**
This removes some hacks and has the potential to fix https://github.com/Dzierzan/OpenSA/issues/128. Maybe also https://github.com/Dzierzan/OpenSA/issues/122.

### CODE REVIEW

**Comment by Dzierzan** [comment]
Alright, I edited mission 036 to get some more units, so I was able to better debug it.

What works:
- looks like after capturing the colony, you can finally build something. Even AI doesn't have this problem anymore.

What needs fixing:
- if you destroy colony, its position totally changes
- you no longer see it on mini map
- turrets are gone
- units can go through destroyed colony
- captured colony should be starting with the half of HP

**Comment by Mailaender** [comment]
I added an `Offset` parameter, but couldn't find suitable values for it.

**Comment by Dzierzan** [comment]
So OK, after some testing, to fix wrong offsets, unclaimed colonies require `HitShape` and `Building` copied from their normal state colony.

However, this still creates an issue of lacking turrets. They can be again copied from normal colony, however, when the colony changes its state to unclaimed one, the position of turrets is not remembered.

Now, when 'HitShape' and 'Building' are there in place, there's a noticable blink between changing states. Interestingly enough, this doesn't always happen. E.g. sometimes you don't see it at all and if you close and run the game again, this issue is visable. Seems very random. Although it is worth noting the blinking only happens when changing state from owned to unowned. There's no blink when it is captured again.

Maybe it is not a clean solution, but some kind of neutral "empty" colony (shouldn't be considered as colony by game logic to avoid problems with winning condition) could be always rendered beneath claimed and unclaimed colony. This way, the blinking issue should be somewhat gone.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/pull/18689 plus followups may be the answer to the colony blinking bug.

**Comment by Mailaender** [comment]
I updated this: `ResurrectHealth` is now taken into account. `HitShape` and `Building` `FootPrint` as well as `HitShape` have been copied over. Changed the interface to `INotifyKilled` which fixes the flickering.

**Comment by Dzierzan** [comment]
Alright. Offset problem is gone.

But this has appeared after you claim the colony:

sa-2020-10-26T173120548Z

**Comment by Mailaender** [comment]
Fixed.

**Comment by Dzierzan** [comment]
Custom turrets have the same issue:
sa-2020-10-26T181639494Z

Turrets are gone when colony is unclaimed:
sa-2020-10-26T181711772Z

Colony or custom turrets are not rendered on the minimap if they are unclaimed. I'd suggest adding `AppearsOnRadar` instead of `CustomAppearsOnRadar` to `^CoreUnclaimedBuilding`, as this custom trait by @IceReaper was never fully finished (unclaimed colony won't be rendered as 6x6 px on the minimap). It should also done for Custom Turrets.

And I noticed something else, since this is based on new engine version, if units are close to each other, they start flickering, like ZOffset is going crazy:
flickering

**Comment by Mailaender** [comment]
Fixed the radar and added fake turrets. https://github.com/OpenRA/OpenRA/pull/18774 will probably fix the Z fighting.

**Comment by Mailaender** [comment]
Fixed turret health.

**Comment by Dzierzan** [comment]
Turret offsets are wrong. Besides, are you sure you want to solve it that way? I mean having a dummy turret is kind of against the original behavior. Or maybe I'll put this way, the position of turret needs to be remembered.

**Comment by Mailaender** [comment]
Turrets now keep their facing and use the positioning of the real counterparts.

**Comment by Dzierzan** [comment]
Unclaimed colony and custom turret lack: 

`	Targetable:
		TargetTypes: Ground, Colony`

Without that, if a bullet is still flying to the already destroyed colony, it will not explode.

**Comment by Mailaender** [comment]
Made them targetable, but also invulnerable now.

**Comment by Dzierzan** [comment]
When custom scorpions' or beetles' turret is unclaimed, you can spot the offset change.

And about flickering. It is random, sometimes it is noticable, sometimes it is not. I am willing to kinda accept that untill proper solution is made.

2nd turret position is not remembered for Spiders and Ants colonies. @Mailaender you said it's an engine limitation. But fixing Dzierzan/OpenSA#10 would helping fixing that issue? Or it's beyond fixing? What about tying turrets together? After certain engine update, they seem to be less tied if you know what I mean.

**Comment by Mailaender** [comment]
Actually the map editor allows to you to set the turrets independently, so I now keep the same for the colonies.

**Pull request merged**
