### PR TITLE
Added a flying creep spawner

### PR DESCRIPTION
**Pull request by Mailaender**
Helps with https://github.com/Dzierzan/SwarmAssault/issues/21 but doesn't solve it yet. Sadly `AttackBomber` crashes which can only be solved at engine level.

### CODE REVIEW

**Comment by GraionDilach** [comment]
What is the idea here?

**Comment by Dzierzan** [comment]
In the original game, there are creep bombers which fly off map and basically bomb the area. See #21

**Comment by GraionDilach** [comment]
I'd omit `AttackBomber` and go with As `ExplodeWeapon` + `FireFragmentWarhead` for reproducing the first gif's pattern and a direct `SpawnsShrapnel` for the rest random patterned ones.

**Comment by Mailaender** [comment]
Rebased and added the `SpawnsShrapnel` from #34.

**Comment by Dzierzan** [comment]
Tested. Works nicely.

**Pull request merged**
