### PR TITLE
Update asset download mirror

### PR DESCRIPTION
**Pull request by Nawias**
Old mirror was dead, so I added a new one.

### CODE REVIEW

**Comment by Dzierzan** [comment]
Actually the old mirror wasn't dead. Just the guy who hosts it for me had to make a maintanance. Nevertheless it is always good to have more mirrors. So, you could bring back old mirror as well in your PR.

**Comment by Nawias** [comment]
Oh, ok, sure

**Comment by Dzierzan** [comment]
So, let's back to this again. This currently replaces the mirror which works fine. Now, I am not an expert here here, but why can't both mirrors be next to each other?

**Comment by Dzierzan** [comment]
@Nawias 
The project has now 3 mirrors. I'll close this PR. If you want to make another mirror, feel free to make a new PR.

**Pull request closed without merging**
