### PR TITLE
Removed tileset duplicates

### PR DESCRIPTION
**Pull request by Mailaender**
`PickAny` now works across tiles so that flood fill and new map fix edges will work with the existing tiles.

### CODE REVIEW

**Comment by Dzierzan** [comment]
Sticks_And_Stones_alternative/map.png  shouldn't be changed.

**Comment by Mailaender** [comment]
Reverted map.png changes and reimported all campaign maps.

**Comment by Dzierzan** [comment]
Desert battleground map seems to have a lot of errors. Hence Github action fails to compile.

**Comment by Mailaender** [comment]
Fixed the remaining maps and update engine version again as https://github.com/OpenRA/OpenRA/pull/19317 may be of interest.

**Pull request merged**
