### PR TITLE
Update map.yaml

### PR DESCRIPTION
**Pull request by wandsmire**
my first PR, hopefully you don't mind... :)

### CODE REVIEW

**Review by Dzierzan — COMMENTED** [review]
Why did you comment out these actors? According to that, only Black Widows will be built.

**Comment by wandsmire** [comment]
> Why did you comment out these actors? According to that, only Black Widows will be built.

Sorry, I forgot to mention this. Mission 6 is nearly impossible to beat if the enemy could build missiles/snipers.

**Comment by Dzierzan** [comment]
I am sorry, but I'll have to close it. I can do the fix myself. I am not going to update original production chances for actors (yes, I got them from Swarm Assault map editor). Besides, note that in your case Spiders faction will only be able to build Black Widows and if they capture a new colony, they won't be able to build anything unless it's another Spiders Colony.
Don't take me wrong though, I did very minor changes to some maps to make them a bit more fair but I still gotta do it for mission like 099 Super Colony.
OpenSA is mainly focused around single player experience and I do like the fact the mod is challenging, otherwise you would blizt through missions like crazy.

I might figure out difficulty options in the future, so production chances, squadsizes and reaction time could be altered.

**Comment by Dzierzan** [comment]
And I just played this mission. It is not really that hard. Just build missiles, attack the Ant creep colony with spiders, if it's destroyed, use your wasps to quickly capture it. Still keep building missiles, fight off the first wave of enemy Spiders (use everything you got). If you did it right, from this point it's gonna be easy, I'd use your missiles to attack the yellow AI while still remembering about defending yourself.

**Comment by wandsmire** [comment]
> I am sorry, but I'll have to close it. I can do the fix myself. I am not going to update original production chances for actors (yes, I got them from Swarm Assault map editor). Besides, note that in your case Spiders faction will only be able to build Black Widows and if they capture a new colony, they won't be able to build anything unless it's another Spiders Colony.
> Don't take me wrong though, I did very minor changes to some maps to make them a bit more fair but I still gotta do it for mission like 099 Super Colony.
> OpenSA is mainly focused around single player experience and I do like the fact the mod is challenging, otherwise you would blizt through missions like crazy.
> 
> I might figure out difficulty options in the future, so production chances, squadsizes and reaction time could be altered.

understood, I'll stay focused on finding bugs. thanks.

**Pull request closed without merging**
