### PR TITLE
Added a custom locomotor for wasps

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/Dzierzan/OpenSA/issues/59.

### CODE REVIEW

**Comment by Dzierzan** [comment]
1. If a wasp flys above water or other actor, you can see it changes its altitude a little bit. In original there's no such behavior.
2. If a wasp is over water, you see see its shadow, it should be disabled (sprites already have baked in shadows).
3. Hovering movement over water should be disabled (it hovers when it is shooting something while still being over water).
4. When a wasp flys over water, it has a significant speed boost, it shouldn't be like that.

**Comment by Dzierzan** [comment]
Two more thoughts:

1. Why the cursor tell me I cannot go on water if Wasps can go there?
2. Despite being able to fly above actors, wasps tend to go around actors.

**Comment by Mailaender** [comment]
Changed the altitude, removed the duplicate shadow, removed hovering, removed the speed boost while in the air, removed the transition cost. The cursor is shown because the wasps can't go there only fly above it.

**Comment by Dzierzan** [comment]
Alright, ZOffset needs to be adjusted. Because while the wasp sprite will be above other actors, it appears it won't be for some decorations.

Altitude change is still visable when wasps try to fly above other actors. That sudden "jump". If it's too hard to adjust that, I can live with that.

**Comment by Dzierzan** [comment]
If you have wasps on water and try to attack something, wasps which are behind will "stand" on water, I suppose it's pathfinding which needs some time to think the shortest route to the target. Anyway, moving state should be always a thing if an actor is over the water.

**Comment by Mailaender** [comment]
I put several checks in place so that attack and movement don't collide. Also, the flight height is zero now.

**Comment by Dzierzan** [comment]
Cool. Those work. But now if you target something which is across water, wasps will just fly there. No attacking the target. This also applies if wasps are already over water and you target something around them. It won't work.

**Comment by Mailaender** [comment]
This is extremely fiddly. I added a new condition and a tiny fake height. It seems pausing the attack animation might be the best option. However, it does not always work and with every wasp actor although their setup looks quite identical.

**Comment by Dzierzan** [comment]
Now they can shoot, but they use idle sprites instead of shooting ones.

**Comment by Mailaender** [comment]
I experimented a bit. Best result was I disallow force firing onto water and firing while in the above water movement layer.

**Pull request merged**
